import { Inter } from "next/font/google";
import "./globals.css";
import vazirFont from "@/constants/localFonts";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${vazirFont.variable}.font-sans`}>
        <Header />
        <div className="contianer xl:max-w-screen-xl"> {children}</div>
      </body>
    </html>
  );
}
