import "../globals.css";
import vazirFont from "@/constants/localFonts";
import { Toaster } from "react-hot-toast";
import Header from "../Header";
import Providers from "../Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        suppressHydrationWarning={true}
        className={`${vazirFont.variable} font-sans`}
      >
        <Providers>
          <Toaster />
          <Header />
          <div className="contianer xl:max-w-screen-xl">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
